// Generated by gencpp from file test_actionlib/rendezvousActionGoal.msg
// DO NOT EDIT!


#ifndef TEST_ACTIONLIB_MESSAGE_RENDEZVOUSACTIONGOAL_H
#define TEST_ACTIONLIB_MESSAGE_RENDEZVOUSACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <test_actionlib/rendezvousGoal.h>

namespace test_actionlib
{
template <class ContainerAllocator>
struct rendezvousActionGoal_
{
  typedef rendezvousActionGoal_<ContainerAllocator> Type;

  rendezvousActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  rendezvousActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::test_actionlib::rendezvousGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct rendezvousActionGoal_

typedef ::test_actionlib::rendezvousActionGoal_<std::allocator<void> > rendezvousActionGoal;

typedef boost::shared_ptr< ::test_actionlib::rendezvousActionGoal > rendezvousActionGoalPtr;
typedef boost::shared_ptr< ::test_actionlib::rendezvousActionGoal const> rendezvousActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_actionlib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'test_actionlib': ['/home/turtle/catkin_ws/src/tutorial_behaviors/test_actionlib/curlpp/devel/share/test_actionlib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0be98f31ac69fe2cc987aef8cf933ad2";
  }

  static const char* value(const ::test_actionlib::rendezvousActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0be98f31ac69fe2cULL;
  static const uint64_t static_value2 = 0xc987aef8cf933ad2ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_actionlib/rendezvousActionGoal";
  }

  static const char* value(const ::test_actionlib::rendezvousActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
rendezvousGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: test_actionlib/rendezvousGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
int32 goal_dist\n\
# This is the resulting distance between each robot after this action is completed\n\
";
  }

  static const char* value(const ::test_actionlib::rendezvousActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rendezvousActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_actionlib::rendezvousActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_actionlib::rendezvousActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ACTIONLIB_MESSAGE_RENDEZVOUSACTIONGOAL_H
