// Generated by gencpp from file test_actionlib/rendezvousGoal.msg
// DO NOT EDIT!


#ifndef TEST_ACTIONLIB_MESSAGE_RENDEZVOUSGOAL_H
#define TEST_ACTIONLIB_MESSAGE_RENDEZVOUSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_actionlib
{
template <class ContainerAllocator>
struct rendezvousGoal_
{
  typedef rendezvousGoal_<ContainerAllocator> Type;

  rendezvousGoal_()
    : goal_dist(0)  {
    }
  rendezvousGoal_(const ContainerAllocator& _alloc)
    : goal_dist(0)  {
  (void)_alloc;
    }



   typedef int32_t _goal_dist_type;
  _goal_dist_type goal_dist;





  typedef boost::shared_ptr< ::test_actionlib::rendezvousGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_actionlib::rendezvousGoal_<ContainerAllocator> const> ConstPtr;

}; // struct rendezvousGoal_

typedef ::test_actionlib::rendezvousGoal_<std::allocator<void> > rendezvousGoal;

typedef boost::shared_ptr< ::test_actionlib::rendezvousGoal > rendezvousGoalPtr;
typedef boost::shared_ptr< ::test_actionlib::rendezvousGoal const> rendezvousGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_actionlib::rendezvousGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_actionlib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test_actionlib': ['/home/turtle/catkin_ws/src/tutorial_behaviors/test_actionlib/curlpp/devel/share/test_actionlib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec461de99ebd8d1840ab95f09c8c0f96";
  }

  static const char* value(const ::test_actionlib::rendezvousGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec461de99ebd8d18ULL;
  static const uint64_t static_value2 = 0x40ab95f09c8c0f96ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_actionlib/rendezvousGoal";
  }

  static const char* value(const ::test_actionlib::rendezvousGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
int32 goal_dist\n\
# This is the resulting distance between each robot after this action is completed\n\
";
  }

  static const char* value(const ::test_actionlib::rendezvousGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rendezvousGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_actionlib::rendezvousGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_actionlib::rendezvousGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_dist: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ACTIONLIB_MESSAGE_RENDEZVOUSGOAL_H
