// Generated by gencpp from file test_actionlib/rendezvousFeedback.msg
// DO NOT EDIT!


#ifndef TEST_ACTIONLIB_MESSAGE_RENDEZVOUSFEEDBACK_H
#define TEST_ACTIONLIB_MESSAGE_RENDEZVOUSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace test_actionlib
{
template <class ContainerAllocator>
struct rendezvousFeedback_
{
  typedef rendezvousFeedback_<ContainerAllocator> Type;

  rendezvousFeedback_()
    : avg_real_dist(0)
    , num_rb(0)
    , stamp()
    , centroid()  {
    }
  rendezvousFeedback_(const ContainerAllocator& _alloc)
    : avg_real_dist(0)
    , num_rb(0)
    , stamp()
    , centroid(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _avg_real_dist_type;
  _avg_real_dist_type avg_real_dist;

   typedef int32_t _num_rb_type;
  _num_rb_type num_rb;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;





  typedef boost::shared_ptr< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct rendezvousFeedback_

typedef ::test_actionlib::rendezvousFeedback_<std::allocator<void> > rendezvousFeedback;

typedef boost::shared_ptr< ::test_actionlib::rendezvousFeedback > rendezvousFeedbackPtr;
typedef boost::shared_ptr< ::test_actionlib::rendezvousFeedback const> rendezvousFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_actionlib::rendezvousFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_actionlib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test_actionlib': ['/home/turtle/catkin_ws/src/tutorial_behaviors/test_actionlib/curlpp/devel/share/test_actionlib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc93f34c8348356787b6d9cf6a90994a";
  }

  static const char* value(const ::test_actionlib::rendezvousFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc93f34c83483567ULL;
  static const uint64_t static_value2 = 0x87b6d9cf6a90994aULL;
};

template<class ContainerAllocator>
struct DataType< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_actionlib/rendezvousFeedback";
  }

  static const char* value(const ::test_actionlib::rendezvousFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
int32 avg_real_dist\n\
int32 num_rb\n\
time stamp\n\
geometry_msgs/Point centroid\n\
# This will show the user how well the behavior is working in real time\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::test_actionlib::rendezvousFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avg_real_dist);
      stream.next(m.num_rb);
      stream.next(m.stamp);
      stream.next(m.centroid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rendezvousFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_actionlib::rendezvousFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_actionlib::rendezvousFeedback_<ContainerAllocator>& v)
  {
    s << indent << "avg_real_dist: ";
    Printer<int32_t>::stream(s, indent + "  ", v.avg_real_dist);
    s << indent << "num_rb: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_rb);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ACTIONLIB_MESSAGE_RENDEZVOUSFEEDBACK_H
