// Generated by gencpp from file test_actionlib/testGoal.msg
// DO NOT EDIT!


#ifndef TEST_ACTIONLIB_MESSAGE_TESTGOAL_H
#define TEST_ACTIONLIB_MESSAGE_TESTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_actionlib
{
template <class ContainerAllocator>
struct testGoal_
{
  typedef testGoal_<ContainerAllocator> Type;

  testGoal_()
    : test_goal()  {
    }
  testGoal_(const ContainerAllocator& _alloc)
    : test_goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _test_goal_type;
  _test_goal_type test_goal;





  typedef boost::shared_ptr< ::test_actionlib::testGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_actionlib::testGoal_<ContainerAllocator> const> ConstPtr;

}; // struct testGoal_

typedef ::test_actionlib::testGoal_<std::allocator<void> > testGoal;

typedef boost::shared_ptr< ::test_actionlib::testGoal > testGoalPtr;
typedef boost::shared_ptr< ::test_actionlib::testGoal const> testGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_actionlib::testGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_actionlib::testGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_actionlib

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'test_actionlib': ['/home/turtle/catkin_ws/src/tutorial_behaviors/test_actionlib/curlpp/devel/share/test_actionlib/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::testGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_actionlib::testGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::testGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_actionlib::testGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::testGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_actionlib::testGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_actionlib::testGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "431931990308709b45979518bdc055cd";
  }

  static const char* value(const ::test_actionlib::testGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x431931990308709bULL;
  static const uint64_t static_value2 = 0x45979518bdc055cdULL;
};

template<class ContainerAllocator>
struct DataType< ::test_actionlib::testGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_actionlib/testGoal";
  }

  static const char* value(const ::test_actionlib::testGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_actionlib::testGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal \n\
string test_goal\n\
";
  }

  static const char* value(const ::test_actionlib::testGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_actionlib::testGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.test_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_actionlib::testGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_actionlib::testGoal_<ContainerAllocator>& v)
  {
    s << indent << "test_goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.test_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_ACTIONLIB_MESSAGE_TESTGOAL_H
