// Auto-generated. Do not edit!

// (in-package test_actionlib.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class rendezvousGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_dist = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_dist')) {
        this.goal_dist = initObj.goal_dist
      }
      else {
        this.goal_dist = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type rendezvousGoal
    // Serialize message field [goal_dist]
    bufferOffset = _serializer.int32(obj.goal_dist, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type rendezvousGoal
    let len;
    let data = new rendezvousGoal(null);
    // Deserialize message field [goal_dist]
    data.goal_dist = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'test_actionlib/rendezvousGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ec461de99ebd8d1840ab95f09c8c0f96';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    int32 goal_dist
    # This is the resulting distance between each robot after this action is completed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new rendezvousGoal(null);
    if (msg.goal_dist !== undefined) {
      resolved.goal_dist = msg.goal_dist;
    }
    else {
      resolved.goal_dist = 0
    }

    return resolved;
    }
};

module.exports = rendezvousGoal;
