// Auto-generated. Do not edit!

// (in-package test_actionlib.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class testFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.test_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('test_feedback')) {
        this.test_feedback = initObj.test_feedback
      }
      else {
        this.test_feedback = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type testFeedback
    // Serialize message field [test_feedback]
    bufferOffset = _serializer.int32(obj.test_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type testFeedback
    let len;
    let data = new testFeedback(null);
    // Deserialize message field [test_feedback]
    data.test_feedback = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'test_actionlib/testFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fa3040db3efe13ae7d434a0ce44bd07b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int32 test_feedback
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new testFeedback(null);
    if (msg.test_feedback !== undefined) {
      resolved.test_feedback = msg.test_feedback;
    }
    else {
      resolved.test_feedback = 0
    }

    return resolved;
    }
};

module.exports = testFeedback;
