// Auto-generated. Do not edit!

// (in-package test_actionlib.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class testGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.test_goal = null;
    }
    else {
      if (initObj.hasOwnProperty('test_goal')) {
        this.test_goal = initObj.test_goal
      }
      else {
        this.test_goal = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type testGoal
    // Serialize message field [test_goal]
    bufferOffset = _serializer.string(obj.test_goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type testGoal
    let len;
    let data = new testGoal(null);
    // Deserialize message field [test_goal]
    data.test_goal = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.test_goal.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'test_actionlib/testGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '431931990308709b45979518bdc055cd';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal 
    string test_goal
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new testGoal(null);
    if (msg.test_goal !== undefined) {
      resolved.test_goal = msg.test_goal;
    }
    else {
      resolved.test_goal = ''
    }

    return resolved;
    }
};

module.exports = testGoal;
