// Auto-generated. Do not edit!

// (in-package test_actionlib.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class testResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.test_result = null;
    }
    else {
      if (initObj.hasOwnProperty('test_result')) {
        this.test_result = initObj.test_result
      }
      else {
        this.test_result = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type testResult
    // Serialize message field [test_result]
    bufferOffset = _serializer.string(obj.test_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type testResult
    let len;
    let data = new testResult(null);
    // Deserialize message field [test_result]
    data.test_result = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.test_result.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'test_actionlib/testResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '453d8fb4bed17e1365cd8990de5cf609';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    string test_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new testResult(null);
    if (msg.test_result !== undefined) {
      resolved.test_result = msg.test_result;
    }
    else {
      resolved.test_result = ''
    }

    return resolved;
    }
};

module.exports = testResult;
