set(_CATKIN_CURRENT_PACKAGE "test_actionlib")
set(test_actionlib_VERSION "0.0.0")
set(test_actionlib_MAINTAINER "keitaro <keitaro@todo.todo>")
set(test_actionlib_PACKAGE_FORMAT "2")
set(test_actionlib_BUILD_DEPENDS "actionlib" "actionlib_msgs" "message_generation" "roscpp" "rospy" "std_msg")
set(test_actionlib_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "rospy" "std_msg")
set(test_actionlib_BUILDTOOL_DEPENDS "catkin")
set(test_actionlib_BUILDTOOL_EXPORT_DEPENDS )
set(test_actionlib_EXEC_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "rospy" "std_msg" "message_generation")
set(test_actionlib_RUN_DEPENDS "actionlib" "actionlib_msgs" "roscpp" "rospy" "std_msg" "message_generation")
set(test_actionlib_TEST_DEPENDS )
set(test_actionlib_DOC_DEPENDS )
set(test_actionlib_URL_WEBSITE "")
set(test_actionlib_URL_BUGTRACKER "")
set(test_actionlib_URL_REPOSITORY "")
set(test_actionlib_DEPRECATED "")