; Auto-generated. Do not edit!


(cl:in-package test_actionlib-msg)


;//! \htmlinclude rendezvousGoal.msg.html

(cl:defclass <rendezvousGoal> (roslisp-msg-protocol:ros-message)
  ((goal_dist
    :reader goal_dist
    :initarg :goal_dist
    :type cl:integer
    :initform 0))
)

(cl:defclass rendezvousGoal (<rendezvousGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rendezvousGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rendezvousGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_actionlib-msg:<rendezvousGoal> is deprecated: use test_actionlib-msg:rendezvousGoal instead.")))

(cl:ensure-generic-function 'goal_dist-val :lambda-list '(m))
(cl:defmethod goal_dist-val ((m <rendezvousGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:goal_dist-val is deprecated.  Use test_actionlib-msg:goal_dist instead.")
  (goal_dist m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rendezvousGoal>) ostream)
  "Serializes a message object of type '<rendezvousGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal_dist)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rendezvousGoal>) istream)
  "Deserializes a message object of type '<rendezvousGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_dist) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rendezvousGoal>)))
  "Returns string type for a message object of type '<rendezvousGoal>"
  "test_actionlib/rendezvousGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rendezvousGoal)))
  "Returns string type for a message object of type 'rendezvousGoal"
  "test_actionlib/rendezvousGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rendezvousGoal>)))
  "Returns md5sum for a message object of type '<rendezvousGoal>"
  "ec461de99ebd8d1840ab95f09c8c0f96")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rendezvousGoal)))
  "Returns md5sum for a message object of type 'rendezvousGoal"
  "ec461de99ebd8d1840ab95f09c8c0f96")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rendezvousGoal>)))
  "Returns full string definition for message of type '<rendezvousGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 goal_dist~%# This is the resulting distance between each robot after this action is completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rendezvousGoal)))
  "Returns full string definition for message of type 'rendezvousGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 goal_dist~%# This is the resulting distance between each robot after this action is completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rendezvousGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rendezvousGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'rendezvousGoal
    (cl:cons ':goal_dist (goal_dist msg))
))
