; Auto-generated. Do not edit!


(cl:in-package test_actionlib-msg)


;//! \htmlinclude rendezvousActionGoal.msg.html

(cl:defclass <rendezvousActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type test_actionlib-msg:rendezvousGoal
    :initform (cl:make-instance 'test_actionlib-msg:rendezvousGoal)))
)

(cl:defclass rendezvousActionGoal (<rendezvousActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rendezvousActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rendezvousActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_actionlib-msg:<rendezvousActionGoal> is deprecated: use test_actionlib-msg:rendezvousActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <rendezvousActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:header-val is deprecated.  Use test_actionlib-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <rendezvousActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:goal_id-val is deprecated.  Use test_actionlib-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <rendezvousActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:goal-val is deprecated.  Use test_actionlib-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rendezvousActionGoal>) ostream)
  "Serializes a message object of type '<rendezvousActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rendezvousActionGoal>) istream)
  "Deserializes a message object of type '<rendezvousActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rendezvousActionGoal>)))
  "Returns string type for a message object of type '<rendezvousActionGoal>"
  "test_actionlib/rendezvousActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rendezvousActionGoal)))
  "Returns string type for a message object of type 'rendezvousActionGoal"
  "test_actionlib/rendezvousActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rendezvousActionGoal>)))
  "Returns md5sum for a message object of type '<rendezvousActionGoal>"
  "0be98f31ac69fe2cc987aef8cf933ad2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rendezvousActionGoal)))
  "Returns md5sum for a message object of type 'rendezvousActionGoal"
  "0be98f31ac69fe2cc987aef8cf933ad2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rendezvousActionGoal>)))
  "Returns full string definition for message of type '<rendezvousActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%rendezvousGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: test_actionlib/rendezvousGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 goal_dist~%# This is the resulting distance between each robot after this action is completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rendezvousActionGoal)))
  "Returns full string definition for message of type 'rendezvousActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%rendezvousGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: test_actionlib/rendezvousGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int32 goal_dist~%# This is the resulting distance between each robot after this action is completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rendezvousActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rendezvousActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'rendezvousActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
