; Auto-generated. Do not edit!


(cl:in-package test_actionlib-msg)


;//! \htmlinclude testFeedback.msg.html

(cl:defclass <testFeedback> (roslisp-msg-protocol:ros-message)
  ((test_feedback
    :reader test_feedback
    :initarg :test_feedback
    :type cl:integer
    :initform 0))
)

(cl:defclass testFeedback (<testFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <testFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'testFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_actionlib-msg:<testFeedback> is deprecated: use test_actionlib-msg:testFeedback instead.")))

(cl:ensure-generic-function 'test_feedback-val :lambda-list '(m))
(cl:defmethod test_feedback-val ((m <testFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:test_feedback-val is deprecated.  Use test_actionlib-msg:test_feedback instead.")
  (test_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <testFeedback>) ostream)
  "Serializes a message object of type '<testFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'test_feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <testFeedback>) istream)
  "Deserializes a message object of type '<testFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'test_feedback) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<testFeedback>)))
  "Returns string type for a message object of type '<testFeedback>"
  "test_actionlib/testFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'testFeedback)))
  "Returns string type for a message object of type 'testFeedback"
  "test_actionlib/testFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<testFeedback>)))
  "Returns md5sum for a message object of type '<testFeedback>"
  "fa3040db3efe13ae7d434a0ce44bd07b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'testFeedback)))
  "Returns md5sum for a message object of type 'testFeedback"
  "fa3040db3efe13ae7d434a0ce44bd07b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<testFeedback>)))
  "Returns full string definition for message of type '<testFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 test_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'testFeedback)))
  "Returns full string definition for message of type 'testFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 test_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <testFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <testFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'testFeedback
    (cl:cons ':test_feedback (test_feedback msg))
))
