; Auto-generated. Do not edit!


(cl:in-package test_actionlib-msg)


;//! \htmlinclude testResult.msg.html

(cl:defclass <testResult> (roslisp-msg-protocol:ros-message)
  ((test_result
    :reader test_result
    :initarg :test_result
    :type cl:string
    :initform ""))
)

(cl:defclass testResult (<testResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <testResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'testResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name test_actionlib-msg:<testResult> is deprecated: use test_actionlib-msg:testResult instead.")))

(cl:ensure-generic-function 'test_result-val :lambda-list '(m))
(cl:defmethod test_result-val ((m <testResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader test_actionlib-msg:test_result-val is deprecated.  Use test_actionlib-msg:test_result instead.")
  (test_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <testResult>) ostream)
  "Serializes a message object of type '<testResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'test_result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'test_result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <testResult>) istream)
  "Deserializes a message object of type '<testResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'test_result) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'test_result) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<testResult>)))
  "Returns string type for a message object of type '<testResult>"
  "test_actionlib/testResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'testResult)))
  "Returns string type for a message object of type 'testResult"
  "test_actionlib/testResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<testResult>)))
  "Returns md5sum for a message object of type '<testResult>"
  "453d8fb4bed17e1365cd8990de5cf609")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'testResult)))
  "Returns md5sum for a message object of type 'testResult"
  "453d8fb4bed17e1365cd8990de5cf609")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<testResult>)))
  "Returns full string definition for message of type '<testResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string test_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'testResult)))
  "Returns full string definition for message of type 'testResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string test_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <testResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'test_result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <testResult>))
  "Converts a ROS message object to a list"
  (cl:list 'testResult
    (cl:cons ':test_result (test_result msg))
))
